# Force Python provider and explicit start to avoid Nixpacks mis-detecting TypeScript from HLS .ts test files
providers = ["python"]
ignorePaths = ["test_root", "test_root/"]

[phases.setup]
nixPkgs = ["python311", "pipx"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements/edx/base.txt"
]

[start]
cmd = "bash scripts/entrypoint.sh"

[variables]
SERVICE = "lms"
PORT = "8000"
WEB_CONCURRENCY = "2"
LOG_LEVEL = "info"
SKIP_ASSETS = "true"
RUN_MIGRATIONS = "false"